apiVersion: v1
kind: Service
metadata:
  name: cilium-operator-service
  namespace: kube-system
spec:
  selector:
    io.cilium/app: operator
    name: cilium-operator
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 18000
