// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSecurityPolicies implements SecurityPolicyInterface
type FakeSecurityPolicies struct {
	Fake *FakeCiliumV2
	ns   string
}

var securitypoliciesResource = v2.SchemeGroupVersion.WithResource("securitypolicies")

var securitypoliciesKind = v2.SchemeGroupVersion.WithKind("SecurityPolicy")

// Get takes name of the securityPolicy, and returns the corresponding securityPolicy object, and an error if there is any.
func (c *FakeSecurityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.SecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(securitypoliciesResource, c.ns, name), &v2.SecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.SecurityPolicy), err
}

// List takes label and field selectors, and returns the list of SecurityPolicies that match those selectors.
func (c *FakeSecurityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v2.SecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(securitypoliciesResource, securitypoliciesKind, c.ns, opts), &v2.SecurityPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.SecurityPolicyList{ListMeta: obj.(*v2.SecurityPolicyList).ListMeta}
	for _, item := range obj.(*v2.SecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested securityPolicies.
func (c *FakeSecurityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(securitypoliciesResource, c.ns, opts))

}

// Create takes the representation of a securityPolicy and creates it.  Returns the server's representation of the securityPolicy, and an error, if there is any.
func (c *FakeSecurityPolicies) Create(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.CreateOptions) (result *v2.SecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(securitypoliciesResource, c.ns, securityPolicy), &v2.SecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.SecurityPolicy), err
}

// Update takes the representation of a securityPolicy and updates it. Returns the server's representation of the securityPolicy, and an error, if there is any.
func (c *FakeSecurityPolicies) Update(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (result *v2.SecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(securitypoliciesResource, c.ns, securityPolicy), &v2.SecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.SecurityPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSecurityPolicies) UpdateStatus(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (*v2.SecurityPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(securitypoliciesResource, "status", c.ns, securityPolicy), &v2.SecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.SecurityPolicy), err
}

// Delete takes name of the securityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeSecurityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(securitypoliciesResource, c.ns, name, opts), &v2.SecurityPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSecurityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(securitypoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2.SecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched securityPolicy.
func (c *FakeSecurityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.SecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(securitypoliciesResource, c.ns, name, pt, data, subresources...), &v2.SecurityPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.SecurityPolicy), err
}
