// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBackendTrafficPolicies implements BackendTrafficPolicyInterface
type FakeBackendTrafficPolicies struct {
	Fake *FakeCiliumV2
	ns   string
}

var backendtrafficpoliciesResource = v2.SchemeGroupVersion.WithResource("backendtrafficpolicies")

var backendtrafficpoliciesKind = v2.SchemeGroupVersion.WithKind("BackendTrafficPolicy")

// Get takes name of the backendTrafficPolicy, and returns the corresponding backendTrafficPolicy object, and an error if there is any.
func (c *FakeBackendTrafficPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.BackendTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(backendtrafficpoliciesResource, c.ns, name), &v2.BackendTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.BackendTrafficPolicy), err
}

// List takes label and field selectors, and returns the list of BackendTrafficPolicies that match those selectors.
func (c *FakeBackendTrafficPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v2.BackendTrafficPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(backendtrafficpoliciesResource, backendtrafficpoliciesKind, c.ns, opts), &v2.BackendTrafficPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v2.BackendTrafficPolicyList{ListMeta: obj.(*v2.BackendTrafficPolicyList).ListMeta}
	for _, item := range obj.(*v2.BackendTrafficPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested backendTrafficPolicies.
func (c *FakeBackendTrafficPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(backendtrafficpoliciesResource, c.ns, opts))

}

// Create takes the representation of a backendTrafficPolicy and creates it.  Returns the server's representation of the backendTrafficPolicy, and an error, if there is any.
func (c *FakeBackendTrafficPolicies) Create(ctx context.Context, backendTrafficPolicy *v2.BackendTrafficPolicy, opts v1.CreateOptions) (result *v2.BackendTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(backendtrafficpoliciesResource, c.ns, backendTrafficPolicy), &v2.BackendTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.BackendTrafficPolicy), err
}

// Update takes the representation of a backendTrafficPolicy and updates it. Returns the server's representation of the backendTrafficPolicy, and an error, if there is any.
func (c *FakeBackendTrafficPolicies) Update(ctx context.Context, backendTrafficPolicy *v2.BackendTrafficPolicy, opts v1.UpdateOptions) (result *v2.BackendTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(backendtrafficpoliciesResource, c.ns, backendTrafficPolicy), &v2.BackendTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.BackendTrafficPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBackendTrafficPolicies) UpdateStatus(ctx context.Context, backendTrafficPolicy *v2.BackendTrafficPolicy, opts v1.UpdateOptions) (*v2.BackendTrafficPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(backendtrafficpoliciesResource, "status", c.ns, backendTrafficPolicy), &v2.BackendTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.BackendTrafficPolicy), err
}

// Delete takes name of the backendTrafficPolicy and deletes it. Returns an error if one occurs.
func (c *FakeBackendTrafficPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(backendtrafficpoliciesResource, c.ns, name, opts), &v2.BackendTrafficPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBackendTrafficPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(backendtrafficpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v2.BackendTrafficPolicyList{})
	return err
}

// Patch applies the patch and returns the patched backendTrafficPolicy.
func (c *FakeBackendTrafficPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.BackendTrafficPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(backendtrafficpoliciesResource, c.ns, name, pt, data, subresources...), &v2.BackendTrafficPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v2.BackendTrafficPolicy), err
}
