// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	"context"
	"time"

	v2 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SecurityPoliciesGetter has a method to return a SecurityPolicyInterface.
// A group's client should implement this interface.
type SecurityPoliciesGetter interface {
	SecurityPolicies(namespace string) SecurityPolicyInterface
}

// SecurityPolicyInterface has methods to work with SecurityPolicy resources.
type SecurityPolicyInterface interface {
	Create(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.CreateOptions) (*v2.SecurityPolicy, error)
	Update(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (*v2.SecurityPolicy, error)
	UpdateStatus(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (*v2.SecurityPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v2.SecurityPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v2.SecurityPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.SecurityPolicy, err error)
	SecurityPolicyExpansion
}

// securityPolicies implements SecurityPolicyInterface
type securityPolicies struct {
	client rest.Interface
	ns     string
}

// newSecurityPolicies returns a SecurityPolicies
func newSecurityPolicies(c *CiliumV2Client, namespace string) *securityPolicies {
	return &securityPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the securityPolicy, and returns the corresponding securityPolicy object, and an error if there is any.
func (c *securityPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v2.SecurityPolicy, err error) {
	result = &v2.SecurityPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("securitypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SecurityPolicies that match those selectors.
func (c *securityPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v2.SecurityPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v2.SecurityPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("securitypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested securityPolicies.
func (c *securityPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("securitypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a securityPolicy and creates it.  Returns the server's representation of the securityPolicy, and an error, if there is any.
func (c *securityPolicies) Create(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.CreateOptions) (result *v2.SecurityPolicy, err error) {
	result = &v2.SecurityPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("securitypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(securityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a securityPolicy and updates it. Returns the server's representation of the securityPolicy, and an error, if there is any.
func (c *securityPolicies) Update(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (result *v2.SecurityPolicy, err error) {
	result = &v2.SecurityPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("securitypolicies").
		Name(securityPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(securityPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *securityPolicies) UpdateStatus(ctx context.Context, securityPolicy *v2.SecurityPolicy, opts v1.UpdateOptions) (result *v2.SecurityPolicy, err error) {
	result = &v2.SecurityPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("securitypolicies").
		Name(securityPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(securityPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the securityPolicy and deletes it. Returns an error if one occurs.
func (c *securityPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("securitypolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *securityPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("securitypolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched securityPolicy.
func (c *securityPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v2.SecurityPolicy, err error) {
	result = &v2.SecurityPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("securitypolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
