apiVersion: v1
kind: Service
metadata:
  name: ratelimit
  labels:
    app: ratelimit
spec:
  clusterIP: 10.0.0.253
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc-port
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: http-debug
      port: 6070
      targetPort: 6070
      protocol: TCP
  selector:
    app: ratelimit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratelimit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratelimit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ratelimit
    spec:
      containers:
        - image: envoyproxy/ratelimit:master # 2022/08/16
          imagePullPolicy: IfNotPresent
          name: ratelimit
          command: ["/bin/ratelimit"]
          env:
            - name: LOG_LEVEL
              value: debug
            - name: REDIS_SOCKET_TYPE
              value: tcp
            - name: REDIS_URL
              value: redis:6379
            - name: USE_STATSD
              value: "false"
            - name: RUNTIME_ROOT
              value: /data
            - name: RUNTIME_SUBDIRECTORY
              value: ratelimit
            - name: RUNTIME_WATCH_ROOT
              value: "false"
            - name: RUNTIME_IGNOREDOTFILES
              value: "true"
            # - name: HOST
            #   value: "::"
            # - name: GRPC_HOST   
            #   value: "::"
            - name: CONFIG_GRPC_XDS_SERVER_URL
              value: "cilium-operator-service.kube-system.svc.cluster.local:18000"
            - name: CONFIG_TYPE
              value: "GRPC_XDS_SOTW"
            - name: CONFIG_GRPC_XDS_NODE_ID
              value: "node1"
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 6070