// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2

// BackendTrafficPolicyListerExpansion allows custom methods to be added to
// BackendTrafficPolicyLister.
type BackendTrafficPolicyListerExpansion interface{}

// BackendTrafficPolicyNamespaceListerExpansion allows custom methods to be added to
// BackendTrafficPolicyNamespaceLister.
type BackendTrafficPolicyNamespaceListerExpansion interface{}

// CiliumClusterwideEnvoyConfigListerExpansion allows custom methods to be added to
// CiliumClusterwideEnvoyConfigLister.
type CiliumClusterwideEnvoyConfigListerExpansion interface{}

// CiliumClusterwideNetworkPolicyListerExpansion allows custom methods to be added to
// CiliumClusterwideNetworkPolicyLister.
type CiliumClusterwideNetworkPolicyListerExpansion interface{}

// CiliumEgressGatewayPolicyListerExpansion allows custom methods to be added to
// CiliumEgressGatewayPolicyLister.
type CiliumEgressGatewayPolicyListerExpansion interface{}

// CiliumEndpointListerExpansion allows custom methods to be added to
// CiliumEndpointLister.
type CiliumEndpointListerExpansion interface{}

// CiliumEndpointNamespaceListerExpansion allows custom methods to be added to
// CiliumEndpointNamespaceLister.
type CiliumEndpointNamespaceListerExpansion interface{}

// CiliumEnvoyConfigListerExpansion allows custom methods to be added to
// CiliumEnvoyConfigLister.
type CiliumEnvoyConfigListerExpansion interface{}

// CiliumEnvoyConfigNamespaceListerExpansion allows custom methods to be added to
// CiliumEnvoyConfigNamespaceLister.
type CiliumEnvoyConfigNamespaceListerExpansion interface{}

// CiliumExternalWorkloadListerExpansion allows custom methods to be added to
// CiliumExternalWorkloadLister.
type CiliumExternalWorkloadListerExpansion interface{}

// CiliumIdentityListerExpansion allows custom methods to be added to
// CiliumIdentityLister.
type CiliumIdentityListerExpansion interface{}

// CiliumLocalRedirectPolicyListerExpansion allows custom methods to be added to
// CiliumLocalRedirectPolicyLister.
type CiliumLocalRedirectPolicyListerExpansion interface{}

// CiliumLocalRedirectPolicyNamespaceListerExpansion allows custom methods to be added to
// CiliumLocalRedirectPolicyNamespaceLister.
type CiliumLocalRedirectPolicyNamespaceListerExpansion interface{}

// CiliumNetworkPolicyListerExpansion allows custom methods to be added to
// CiliumNetworkPolicyLister.
type CiliumNetworkPolicyListerExpansion interface{}

// CiliumNetworkPolicyNamespaceListerExpansion allows custom methods to be added to
// CiliumNetworkPolicyNamespaceLister.
type CiliumNetworkPolicyNamespaceListerExpansion interface{}

// CiliumNodeListerExpansion allows custom methods to be added to
// CiliumNodeLister.
type CiliumNodeListerExpansion interface{}

// SecurityPolicyListerExpansion allows custom methods to be added to
// SecurityPolicyLister.
type SecurityPolicyListerExpansion interface{}

// SecurityPolicyNamespaceListerExpansion allows custom methods to be added to
// SecurityPolicyNamespaceLister.
type SecurityPolicyNamespaceListerExpansion interface{}
